### ISSUE TITLE
Adding More Classes

### ISSUE THREAD

**Issue by tbrown2** [sarahmehmedi/comp330_twitterparser#1]
I really like how succinct you get the idea of a tweet parser across. To expand further on some of the properties and design of your code you might want to consider adding some classes to model the tweet, mention, etc.

**Comment by jthompson18** [comment]
@tbrown2 I don't think more classes are inherently necessary. I wouldn't recommend making more than one other class for the tweet. Making classes for each tweet field would be over engineering this.

**Comment by sarahmehmedi** [comment]
@tbrown2 @jthompson18 Thanks for the feedback! I will think about separating into different class if I decide to add more to the different functions!
