### ISSUE TITLE
URL Verification

### ISSUE THREAD

**Issue by dallen4** [sarahmehmedi/comp330_twitterparser#3]
I have concerns about how you identify URLs in the tweet string. Your parsing function seems fairly efficient with simple structure, but these three options don't necessarily cover all the potential URL formats. Furthermore, when a tweet is posted it is parsed in the API and _any_ URL is automatically fitted to 23 chars with a t.co format that is down in-house by Twitter. The line below shows your checks for "http://", "www.", or "https://".

(TwitterParser.java, line 31)
            else if (token.startsWith("http://")|| token.startsWith("www.") || token.startsWith("https://")){

I would suggest maybe considering adding a "t.co" check, but I used regex for this part and checked for long and shortened URLs.

**Comment by sarahmehmedi** [comment]
@dallen4 Thanks for the feedback! I did not take into consideration how Twitter has t.co type shortening for links! To be honest, I didn't even know it existed! I will look into t.co but it seems like I have got the basics of capturing links. It could be something to add onto if this project is more well-defined later on.
