### ISSUE TITLE
Check for invalidity

### ISSUE THREAD

**Issue by aksharkkumar** [sarahmehmedi/comp330_twitterparser#4]
I like the approach you have taken to this problem. The code is clean and easy to follow, which is a very important characteristic of good software. If I were to add an improvement, I would say expand the checks you have to discriminate between a valid and invalid mention, topic and url. Just checking if a word in the message has a '@' symbol in front of it is not all that comprises of a mention. I think if you did more research on the rules for valid and invalid mentions, topics and URLs, you could create a more robust parser that follows the syntax rules of a tweet. Also, once you include more discriminatory rules, make sure you test them out. But what you have is a great start.

**Comment by sarahmehmedi** [comment]
@akkumar93 Thanks for the feedback! I did not really think about certain problems that might occur if someone did "@#" or vice versa, thanks for opening my eyes to what other issues could occur in the Twitter world! I will try and add a few more cases to test for those odd cases. I have added some tests to tests for those @#, #@ factors! Thanks again for the input!
