### ISSUE TITLE
use .gitignore to avoid committing compiled code

### ISSUE THREAD

**Issue by sshilpika** [sarahmehmedi/comp330_twitterparser#6]
Make sure you don't commit files that can be generated from files that are already committed.
[Github best practices](https://gist.github.com/SethRobertson/1540906/68feeabfe906ec1eb893e4fa45f402795ed6e62c#dont)

**Comment by sarahmehmedi** [comment]
Thanks for letting me know about gitignore! I had no idea what it was but now I know! 
-Added .gitignore
